--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Raj/wallpapers/4.jpg"

-- Special
background="#0f1217"
foreground="#ebe5da"
cursor="#ebe5da"

-- Colors
color0="#0f1217"
color1="#CC936E"
color2="#897D81"
color3="#7C989F"
color4="#9D9E9A"
color5="#DAAB91"
color6="#F2D9A6"
color7="#ebe5da"
color8="#a4a098"
color9="#CC936E"
color10="#897D81"
color11="#7C989F"
color12="#9D9E9A"
color13="#DAAB91"
color14="#F2D9A6"
color15="#ebe5da"
