# Shell variables
# Generated by 'wal'
wallpaper='/home/raj/wallpapers/31.jpg'

# Special
background='#0b1b15'
foreground='#e7ebe1'
cursor='#e7ebe1'

# Colors
color0='#0b1b15'
color1='#A2A164'
color2='#A6C868'
color3='#CAC96E'
color4='#73AD87'
color5='#ACC999'
color6='#D6DDA2'
color7='#e7ebe1'
color8='#a1a49d'
color9='#A2A164'
color10='#A6C868'
color11='#CAC96E'
color12='#73AD87'
color13='#ACC999'
color14='#D6DDA2'
color15='#e7ebe1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
