--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Raj/wallpapers/1.jpg"

-- Special
background="#0C0B0A"
foreground="#ddd4cf"
cursor="#ddd4cf"

-- Colors
color0="#0C0B0A"
color1="#756C67"
color2="#847A74"
color3="#8D837C"
color4="#867F80"
color5="#968C86"
color6="#AEA19A"
color7="#ddd4cf"
color8="#9a9490"
color9="#756C67"
color10="#847A74"
color11="#8D837C"
color12="#867F80"
color13="#968C86"
color14="#AEA19A"
color15="#ddd4cf"
