foreground   #e7ebe1
background   #0b1b15
cursor       #e7ebe1

color0       #0b1b15
color8       #a1a49d
color1       #A2A164
color9       #A2A164
color2       #A6C868
color10      #A6C868
color3       #CAC96E
color11      #CAC96E
color4       #73AD87
color12      #73AD87
color5       #ACC999
color13      #ACC999
color6       #D6DDA2
color14      #D6DDA2
color7       #e7ebe1
color15      #e7ebe1
