# Shell variables
# Generated by 'wal'
wallpaper='/home/raj/wallpapers/7889565.jpg'

# Special
background='#0E0316'
foreground='#d99cca'
cursor='#d99cca'

# Colors
color0='#0E0316'
color1='#900012'
color2='#A20228'
color3='#A10B58'
color4='#C22D52'
color5='#CE0561'
color6='#762C8A'
color7='#d99cca'
color8='#976d8d'
color9='#900012'
color10='#A20228'
color11='#A10B58'
color12='#C22D52'
color13='#CE0561'
color14='#762C8A'
color15='#d99cca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
