foreground   #d99cca
background   #0E0316
cursor       #d99cca

color0       #0E0316
color8       #976d8d
color1       #900012
color9       #900012
color2       #A20228
color10      #A20228
color3       #A10B58
color11      #A10B58
color4       #C22D52
color12      #C22D52
color5       #CE0561
color13      #CE0561
color6       #762C8A
color14      #762C8A
color7       #d99cca
color15      #d99cca
