# Shell variables
# Generated by 'wal'
wallpaper='/home/Raj/wallpapers/1.jpg'

# Special
background='#010102'
foreground='#b3cbdb'
cursor='#b3cbdb'

# Colors
color0='#010102'
color1='#354A5F'
color2='#4C596E'
color3='#3E6886'
color4='#5B728E'
color5='#8F7D96'
color6='#6C8EAA'
color7='#b3cbdb'
color8='#7d8e99'
color9='#354A5F'
color10='#4C596E'
color11='#3E6886'
color12='#5B728E'
color13='#8F7D96'
color14='#6C8EAA'
color15='#b3cbdb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
