--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/raj/wallpapers/31.jpg"

-- Special
background="#0b1b15"
foreground="#e7ebe1"
cursor="#e7ebe1"

-- Colors
color0="#0b1b15"
color1="#A2A164"
color2="#A6C868"
color3="#CAC96E"
color4="#73AD87"
color5="#ACC999"
color6="#D6DDA2"
color7="#e7ebe1"
color8="#a1a49d"
color9="#A2A164"
color10="#A6C868"
color11="#CAC96E"
color12="#73AD87"
color13="#ACC999"
color14="#D6DDA2"
color15="#e7ebe1"
